// <auto-generated />
using System;
using Hackathon_Team5_19_21.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace Hackathon_Team5_19_21.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20200618132845_init")]
    partial class init
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "3.1.4");

            modelBuilder.Entity("Hackathon_Team5_19_21.Data.Amministratore", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Cognome")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Password")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<bool>("PrimaPassword")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("Email")
                        .IsUnique();

                    b.ToTable("Amministratori");
                });

            modelBuilder.Entity("Hackathon_Team5_19_21.Data.Citta", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int?>("IdProvincia")
                        .IsRequired()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("IdProvincia");

                    b.ToTable("Citta");
                });

            modelBuilder.Entity("Hackathon_Team5_19_21.Data.Corso", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("AnnoFine")
                        .HasColumnType("INTEGER");

                    b.Property<int>("AnnoInizio")
                        .HasColumnType("INTEGER");

                    b.Property<int?>("IdCitta")
                        .IsRequired()
                        .HasColumnType("INTEGER");

                    b.Property<int?>("IdOrganizzatore")
                        .IsRequired()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("IdCitta");

                    b.HasIndex("IdOrganizzatore");

                    b.ToTable("Corsi");
                });

            modelBuilder.Entity("Hackathon_Team5_19_21.Data.Esame", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<DateTime?>("Data")
                        .HasColumnType("TEXT");

                    b.Property<int?>("IdModulo")
                        .IsRequired()
                        .HasColumnType("INTEGER");

                    b.Property<int?>("IdStudenteIscritto")
                        .IsRequired()
                        .HasColumnType("INTEGER");

                    b.Property<int>("Voto")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("IdModulo");

                    b.HasIndex("IdStudenteIscritto", "IdModulo")
                        .IsUnique();

                    b.ToTable("Esami");
                });

            modelBuilder.Entity("Hackathon_Team5_19_21.Data.Modulo", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<DateTime?>("DataFine")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("DataInizio")
                        .HasColumnType("TEXT");

                    b.Property<int?>("IdCorso")
                        .IsRequired()
                        .HasColumnType("INTEGER");

                    b.Property<int?>("IdDocente")
                        .IsRequired()
                        .HasColumnType("INTEGER");

                    b.Property<int?>("IdTutor")
                        .IsRequired()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Materia")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("IdCorso");

                    b.HasIndex("IdDocente");

                    b.HasIndex("IdTutor");

                    b.ToTable("Moduli");
                });

            modelBuilder.Entity("Hackathon_Team5_19_21.Data.PersonaFitstic", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Cognome")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("DataAssunzione")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("DataNascita")
                        .HasColumnType("TEXT");

                    b.Property<bool>("Docente")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int?>("IdAmministratore")
                        .IsRequired()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<bool>("Organizzatore")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Password")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<bool>("PrimaPassword")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Telefono")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasMaxLength(10);

                    b.Property<bool>("Tutor")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("Email")
                        .IsUnique();

                    b.HasIndex("IdAmministratore");

                    b.ToTable("PersonaleFitstic");
                });

            modelBuilder.Entity("Hackathon_Team5_19_21.Data.Provincia", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Sigla")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Province");
                });

            modelBuilder.Entity("Hackathon_Team5_19_21.Data.Studente", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("AnnoDiploma")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Civico")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Cognome")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("DataNascita")
                        .HasColumnType("TEXT");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int?>("IdCitta")
                        .IsRequired()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Indirizzo")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Password")
                        .HasColumnType("TEXT");

                    b.Property<string>("Telefono")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("TipoDiploma")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("IdCitta");

                    b.ToTable("Studenti");
                });

            modelBuilder.Entity("Hackathon_Team5_19_21.Data.StudenteIscritto", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("DataIscrizione")
                        .HasColumnType("TEXT");

                    b.Property<int?>("IdCorso")
                        .IsRequired()
                        .HasColumnType("INTEGER");

                    b.Property<int?>("IdStudente")
                        .IsRequired()
                        .HasColumnType("INTEGER");

                    b.Property<bool>("NonAmmesso")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("Ritirato")
                        .HasColumnType("INTEGER");

                    b.Property<int>("VotoFinale")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("IdCorso");

                    b.HasIndex("IdStudente");

                    b.ToTable("StudentiIscritti");
                });

            modelBuilder.Entity("Hackathon_Team5_19_21.Data.Citta", b =>
                {
                    b.HasOne("Hackathon_Team5_19_21.Data.Provincia", "Provincia")
                        .WithMany("Citta")
                        .HasForeignKey("IdProvincia")
                        .HasConstraintName("ForeignKey_Provincia_Citta")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Hackathon_Team5_19_21.Data.Corso", b =>
                {
                    b.HasOne("Hackathon_Team5_19_21.Data.Citta", "Citta")
                        .WithMany("Corsi")
                        .HasForeignKey("IdCitta")
                        .HasConstraintName("ForeignKey_Corso_Citta")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Hackathon_Team5_19_21.Data.PersonaFitstic", "Organizzatore")
                        .WithMany("CorsiOrganizzatore")
                        .HasForeignKey("IdOrganizzatore")
                        .HasConstraintName("ForeignKey_Corso_Organizzatore")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Hackathon_Team5_19_21.Data.Esame", b =>
                {
                    b.HasOne("Hackathon_Team5_19_21.Data.Modulo", "Modulo")
                        .WithMany("Esami")
                        .HasForeignKey("IdModulo")
                        .HasConstraintName("ForeignKey_Modulo_Esame")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Hackathon_Team5_19_21.Data.StudenteIscritto", "StudenteIscritto")
                        .WithMany("Esami")
                        .HasForeignKey("IdStudenteIscritto")
                        .HasConstraintName("ForeignKey_Esame_StudenteIscritto")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Hackathon_Team5_19_21.Data.Modulo", b =>
                {
                    b.HasOne("Hackathon_Team5_19_21.Data.Corso", "Corso")
                        .WithMany("Moduli")
                        .HasForeignKey("IdCorso")
                        .HasConstraintName("ForeignKey_Modulo_Corso")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Hackathon_Team5_19_21.Data.PersonaFitstic", "Docente")
                        .WithMany("ModuliDocente")
                        .HasForeignKey("IdDocente")
                        .HasConstraintName("ForeignKey_Modulo_Docente")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Hackathon_Team5_19_21.Data.PersonaFitstic", "Tutor")
                        .WithMany("ModuliTutor")
                        .HasForeignKey("IdTutor")
                        .HasConstraintName("ForeignKey_Modulo_Tutor")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Hackathon_Team5_19_21.Data.PersonaFitstic", b =>
                {
                    b.HasOne("Hackathon_Team5_19_21.Data.Amministratore", "Amministratore")
                        .WithMany("PersonaleFistic")
                        .HasForeignKey("IdAmministratore")
                        .HasConstraintName("ForeignKey_Amministratore_PersonaFitstic")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Hackathon_Team5_19_21.Data.Studente", b =>
                {
                    b.HasOne("Hackathon_Team5_19_21.Data.Citta", "Citta")
                        .WithMany("Studenti")
                        .HasForeignKey("IdCitta")
                        .HasConstraintName("ForeignKey_Studente_Citta")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Hackathon_Team5_19_21.Data.StudenteIscritto", b =>
                {
                    b.HasOne("Hackathon_Team5_19_21.Data.Corso", "Corso")
                        .WithMany("StudentiIscritti")
                        .HasForeignKey("IdCorso")
                        .HasConstraintName("ForeignKey_Corso_StudenteIscritto")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Hackathon_Team5_19_21.Data.Studente", "Studente")
                        .WithMany("StudentiIscritti")
                        .HasForeignKey("IdStudente")
                        .HasConstraintName("ForeignKey_Studente_StudenteIscritto")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });
#pragma warning restore 612, 618
        }
    }
}
